server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


spring:
  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/user/**
          filters:
            - AuthenticationFilter
        - id: AuthenticationService
          uri: lb://AuthenticationService
          predicates:
            - Path=/auth/**
          filters:
            - AuthenticationFilter
  application:
    name: API-GATEWAY
jwt_secret: "3aabc2c36ff8975d5eb8aea77d2c7e0f534e4010a079f18adbc9ae90691b6918"