server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://192.168.29.188:5432/tester
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  liquibase:
    enabled: true
    drop-first: true
    change-log: classpath:db/changelog/backend-master-changelog.xml
